### PR TITLE
Quick pull request resolving #8 now pytorch 1.13.1 is released

### PR DESCRIPTION
**Pull request by philswatton**
Installation now works fine without OS/architecture-specific URLs

### CODE REVIEW

**Comment by lannelin** [comment]
just pulling down to verify on my x86 mac with a fresh environment install, @philswatton have you verified the same on your ARM-based laptop?

**Review by lannelin — COMMENTED** [review]
can confirm this works on my x86 mac with fresh poetry environment
once `poetry install` was complete I was able to run tests successfully.

(I'm a bit surprised it didn't complain about the arm specific stuff in `poetry.lock` but will take the win!)

haven't "approved" as think should be verified on an arm machine first but then happy for this to be merged. Nice one.

**Review by jack89roberts — APPROVED** [review]
```bash
poetry install
poetry run pytest
```

works for me too (x86 Mac). I do get a load of warnings from `pl_bolts` though:

```
pl_bolts/callbacks/data_monitor.py:20: UnderReviewWarning: The feature warn_missing_pkg is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
    warn_missing_pkg("wandb")

pl_bolts/models/self_supervised/amdim/amdim_module.py:35: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
    "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),

pl_bolts/models/self_supervised/amdim/amdim_module.py:93: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
    contrastive_task: Union[FeatureMapContrastiveTask] = FeatureMapContrastiveTask("01, 02, 11"),

pl_bolts/losses/self_supervised_learning.py:234: UnderReviewWarning: The feature AmdimNCELoss is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
    self.nce_loss = AmdimNCELoss(tclip)

pl_bolts/datamodules/experience_source.py:18: UnderReviewWarning: The feature warn_missing_pkg is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
    warn_missing_pkg("gym")

pl_bolts/callbacks/vision/confused_logit.py:16: UnderReviewWarning: The feature warn_missing_pkg is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
    warn_missing_pkg("matplotlib")
```

**Comment by lannelin** [comment]
ah yes these warnings are annoying. @philswatton maybe worth a quick look but if it's not trivial to fix (or filter/ignore) then let's raise a separate issue and come back to it when we've got some time.

**Comment by philswatton** [comment]
Happy to confirm all tests still pass on my arm laptop

I've added a filter to pytest. We still get the count of warnings (106) but they're no longer printed out when testing. They're all `UnderReviewWarning` from `pl_bolts.utils.stability` (and therefore from `from pl_bolts.datamodules import CIFAR10DataModule`, l4 in `src/modsim2/data/loader.py`) as far as I can tell, as after adding that filter no more warnings are printed out

Will merge the PR now

**Comment by philswatton** [comment]
> Happy to confirm all tests still pass on my arm laptop
> 
> I've added a filter to pytest. We still get the count of warnings (106) but they're no longer printed out when testing. They're all `UnderReviewWarning` from `pl_bolts.utils.stability` (and therefore from `from pl_bolts.datamodules import CIFAR10DataModule`, l4 in `src/modsim2/data/loader.py`) as far as I can tell, as after adding that filter no more warnings are printed out
> 
> Will merge the PR now

At least no more are printed out while running pytest - they'll still print to console when running python outside of that!

**Pull request merged**
